Create  database tables
alexiscyber14/DATABSE-BASICS pull request #3
Opened 2023-05-08 18:29 UTC by alexiscyber14

Create tables and queries

2023-05-08 22:16 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @alexiscyber14 👋, 
![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! :running_man: :runner: 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Use correct Gitflow
- ✔️ Use SQL commands

## Required Changes ♻️
_Please kindly check the comments under the review._

[REQUIRE] - I'm unable to add an inline comment to your readme file, so kindly check my comment below: 

![image](https://user-images.githubusercontent.com/78251927/236948929-89c93b24-5351-47fb-9696-fa348c571b79.png)

Please kindly fix the broken link to your `Instagram` account, 👍

Let's avoid broken links in our readme for a professional repository 🤗

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-08 22:16 UTC, abdulhamiid commented on queries.sql
> +WHERE owners.full_name = 'Dean Winchester' AND animals.escape_attempts = 0;
Please kindly add the screenshot with the correct result of this query 👍 

Your screenshot. 👇 
https://github.com/alexiscyber14/DATABSE-BASICS/pull/3/files#diff-41f569b99c5dd18722be9654ec4c30ca3730faf33a16652a253b45363d297c58

2023-05-09 06:56 UTC, alexiscyber14 commented on queries.sql
> +WHERE owners.full_name = 'Dean Winchester' AND animals.escape_attempts = 0;
@abdulhamiid the query returns empty because all the animals he owns have tried to escape and so no data should be returned from the table. one of his animals ecaped once en another escaped 7 times

2023-05-09 07:11 UTC, Davidosky007 requested changes
Hi @alexiscyber14 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
* Good looking readme 👍 
* Proper use of Gitflow 👍 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidosky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-09 07:11 UTC, Davidosky007 commented on queries.sql
> +WHERE owners.full_name = 'Dean Winchester' AND animals.escape_attempts = 0;
* As mentioned by the previous CR its a [requirement](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_query_multiple_tables.md#:~:text=Take%20a%20screenshot,Pull%20Request%20description.) to include screenshots of the results of your queries in your PR  , Kindly add them

2023-05-09 07:15 UTC, abdulhamiid commented on queries.sql
> +WHERE owners.full_name = 'Dean Winchester' AND animals.escape_attempts = 0;
Hi @alexiscyber14

2023-05-09 07:24 UTC, abdulhamiid commented on queries.sql
> +WHERE owners.full_name = 'Dean Winchester' AND animals.escape_attempts = 0;
Hello, @alexiscyber14, I'm sorry for misunderstanding your query result. 

Please kindly add all your screenshots in your PR for easier access as required in the project requirements so that the next reviewer will approve your project. 🤗👍

![image](https://user-images.githubusercontent.com/78251927/237024017-56015d6f-e4cb-41ed-8091-5dd0bc2c6096.png)

2023-05-09 07:46 UTC, alexiscyber14 commented
@Davidosky007 can you please look at the comment i left the last reviewer and then please tell me whats wrog because am confused

2023-05-09 07:48 UTC, alexiscyber14 commented on queries.sql
> +WHERE owners.full_name = 'Dean Winchester' AND animals.escape_attempts = 0;
@abdulhamiid the data is supposed to return nothing the very screenshot you were referencing is the one showing the empty table, so whats going on. how is it supposed to be, is it supposed to return something else?

2023-05-09 07:49 UTC, alexiscyber14 commented
@ @Davidosky007 i put the screen shot there, even the last reviewer referenced it. so am confused. The query isnt supposed to return anything and so the screen shot reflects that with an empty return, so am confused, how is it supposed to be?

2023-05-09 08:36 UTC, Munsa1 requested changes
Hi @alexiscyber14, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Correct GitHub Flow :heavy_check_mark: 
Descriptive ReadMe File :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-09 08:36 UTC, Munsa1 commented on queries.sql
> +WHERE owners.full_name = 'Dean Winchester' AND animals.escape_attempts = 0;
- [ ] As requested by the previous reviewers, its a [requirement](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_query_multiple_tables.md#:~:text=Take%20a%20screenshot,Pull%20Request%20description.) to include screenshots of the results of your queries in your PR, Kindly add them
- [ ] If you are wondering how to do that, it's fairly easy, follow the following steps:
1. Click the three dots to the right of your PR description 
![image](https://user-images.githubusercontent.com/81932478/237041207-1bf4ed0b-a143-4cef-960c-037425aff83c.png)
2. Click edit
3. Add Queries and screenshots as required, it should look something like this, e.g.
![image](https://user-images.githubusercontent.com/81932478/237040775-9ab83f37-a4f3-467d-a273-73410ce932bf.png)

2023-05-09 09:01 UTC, abdulhamiid commented on queries.sql
> +WHERE owners.full_name = 'Dean Winchester' AND animals.escape_attempts = 0;
> @abdulhamiid the data is supposed to return nothing the very screenshot you were referencing is the one showing the empty table, so whats going on. how is it supposed to be, is it supposed to return something else?

Hi @alexiscyber14, what is delaying your project approval is adding screenshot to you pull request summary and i can see you have already done that. :100: :+1:

2023-05-09 09:14 UTC, merged